# Generated by Django 4.2.4 on 2023-08-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastcancerdata',
            name='name',
            field=models.CharField(default='TestPatient', max_length=200),
        ),
    ]
